# Generated by Django 4.2.27 on 2026-01-31 11:14

import core.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Confession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_encrypted', core.fields.EncryptedTextField(help_text='The confession text, encrypted in the DB.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='confessions/')),
                ('mood', models.CharField(default='neutral', help_text='e.g., love, funny, angry', max_length=50)),
                ('ip_hash', models.CharField(help_text="SHA-256 hash of the sender's IP address", max_length=64)),
                ('is_read', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='If recipient chooses to showcase this')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_confessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
